name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@9accbba5cd7c600c1db8051493b1d3c5698187ff # v0.4.1
    secrets: inherit
